# Generated by Django 5.0.5 on 2024-05-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contentn',
            new_name='content',
        ),
    ]
